checks:
    - specification
    - branch_release
    - codevalidator
    - protect_master
specification:
    allowed_schemes: ['https']
    allowed_formats: ['uri', 'github']
branch-release:
    pattern: '^v(?:\d|\_|\.)+$'
